In [1]:
# (i) Creating Different Types of NumPy Arrays and Displaying Basic Information
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)
print("Data Type:", array_1d.dtype)
print("Shape:", array_1d.shape)
print("Size:", array_1d.size)
print("Strides:", array_1d.strides)

# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(array_2d)
print("Data Type:", array_2d.dtype)
print("Shape:", array_2d.shape)
print("Size:", array_2d.size)
print("Strides:", array_2d.strides)


1D Array:
[1 2 3 4 5]
Data Type: int64
Shape: (5,)
Size: 5
Strides: (8,)

2D Array:
[[1 2 3]
 [4 5 6]]
Data Type: int64
Shape: (2, 3)
Size: 6
Strides: (24, 8)


In [2]:
# (ii) Creating an Array Using Built-in NumPy Functions
# Create an array with zeros
zeros_array = np.zeros((3, 4))
print("\nZeros Array:")
print(zeros_array)

# Create an array with ones
ones_array = np.ones((2, 3))
print("\nOnes Array:")
print(ones_array)

# Create an identity matrix
identity_matrix = np.eye(3)
print("\nIdentity Matrix:")
print(identity_matrix)



Zeros Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]]

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
# (iii) Performing File Operations with NumPy Arrays
# Save array to a file
np.save('array_file.npy', array_2d)

# Load array from a file
loaded_array = np.load('array_file.npy')
print("\nLoaded Array from File:")
print(loaded_array)



Loaded Array from File:
[[1 2 3]
 [4 5 6]]


In [1]:
# Arthimetic Oprations on Numpy Arrays : 
import numpy as np

# Creating NumPy arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Addition
result_addition = arr1 + arr2
print("Addition:")
print(result_addition)

# Subtraction
result_subtraction = arr1 - arr2
print("\nSubtraction:")
print(result_subtraction)

# Multiplication
result_multiplication = arr1 * arr2
print("\nMultiplication:")
print(result_multiplication)

# Division
result_division = arr1 / arr2
print("\nDivision:")
print(result_division)

# Element-wise square root
result_sqrt = np.sqrt(arr1)
print("\nSquare Root:")
print(result_sqrt)

# Element-wise exponentiation
result_exp = np.exp(arr1)
print("\nExponentiation:")
print(result_exp)


Addition:
[ 6  8 10 12]

Subtraction:
[-4 -4 -4 -4]

Multiplication:
[ 5 12 21 32]

Division:
[0.2        0.33333333 0.42857143 0.5       ]

Square Root:
[1.         1.41421356 1.73205081 2.        ]

Exponentiation:
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [2]:
#  Broadcasting
# Broadcasting example
arr3 = np.array([2, 2, 2, 2])

# Adding a scalar to an array
result_broadcasting = arr1 + arr3
print("\nBroadcasting:")
print(result_broadcasting)



Broadcasting:
[3 4 5 6]
